name: Coding style checks

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
      - develop
  pull_request:

jobs:
  check_linting:
    name: Check sources linting
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_lint.yml@v1
    with:
      source: './src'
      extensions: 'h,c'
      version: 11

  tests_lint_check:
    name: Check tests linting
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v3
    - run: pip install yapf toml
    - name: Yapf source formatting
      run: |
        yapf test/ --recursive -d
