name: Run coding style check through reusable workflow

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
      - develop
  pull_request:

jobs:
  check_linting:
    name: Check linting
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_lint.yml@v1
    with:
      source: './src'
      extensions: 'h,c'
      version: 11
