name: Ensure compliance with Ledger guidelines

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
      - develop
  pull_request:

jobs:
  guidelines_enforcer:
    name: Guidelines_enforcer
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_guidelines_enforcer.yml@v1
